package com.paradoxgameconverters.batoir;
import java.util.ArrayList;

public class Country
{
    private int id; //numerical ID in save file separate from 3-letter tag
    private String culture;
    private String religion;
    private String loc;
    private String adj;
    private String tag;
    private String historicalTag;
    private String capital;
    private String flag;
    private String color;
    private String ruler;
    private boolean hasLand;
    private String updatedTag; //tag generated by algorithm, to prevent conflict with basegame I:R tags
    private String government;
    private ArrayList<Integer> majorFamilies;
    private ArrayList<String> majorFamiliesStr;
    private String missions; //use missions from x tag
    private boolean antagonist;
    private ArrayList<String[]> laws;
    private int militaryTech;
    private int civicTech;
    private int oratoryTech;
    private int religiousTech;
    public Country() {
        int id;
        String culture;
        String religion;
        String loc;
        String adj;
        String tag;
        String historicalTag;
        String capital;
        String flag;
        String color;
        String ruler;
        boolean hasLand;
        String updatedTag;
        ArrayList<Integer> majorFamilies;
        ArrayList<String> majorFamiliesStr;
        boolean antagonist;
        ArrayList<String[]> laws;
        int militaryTech;
        int civicTech;
        int oratoryTech;
        int religiousTech;
    }
    public void setGovernment(String name) {
        government = name;
    }
    public String getGovernment() {
        return government;
    }
    public void setUpdatedTag(String name) {
        updatedTag = name;
    }
    public String getUpdatedTag() {
        return updatedTag;
    }
    
    public void setHasLand(boolean yn) {
        hasLand = yn;
    }
    public boolean getHasLand() {
        return hasLand;
    }
    public void setHistoricalTag(String name) {
        historicalTag = name;
    }
    public String getHistoricalTag() {
        return historicalTag;
    }
    public void setCapital(String name) {
        capital = name;
    }
    public String getCapital() {
        return capital;
    }
    public void setFlag(String name) {
        flag = name;
    }
    public String getFlag() {
        return flag;
    }
    public void setColor(String name) {
        color = name;
    }
    public String getColor() {
        return color;
    }
    public void setRuler(String name) {
        ruler = name;
    }
    public String getRuler() {
        return ruler;
    }
    
    public void setID(int popID) {
        id = popID;
    }
    public int getID() {
        return id;
    }
    
    public void setLoc(String name) {
        loc = name;
    }
    public String getLoc() {
        return loc;
    }
    public void setAdj(String name) {
        adj = name;
    }
    public String getAdj() {
        return adj;
    }
    
    public void setCulture(String name) {
        culture = name;
    }
    public String getCulture() {
        return culture;
    }
    
    public void setReligion(String name) {
        religion = name;
    }
    public String getReligion() {
        return religion;
    }
    
    public void setTag(String name) {
        tag = name;
    }
    public String getTag() {
        return tag;
    }
    
    public void setMajorFamilies(ArrayList<Integer> families) {
        majorFamilies = families;
    }
    public ArrayList<Integer> getMajorFamilies() {
        return majorFamilies;
    }
    
    public void setMajorFamiliesStr(ArrayList<String> families) {
        majorFamiliesStr = families;
    }
    public ArrayList<String> getMajorFamiliesStr() {
        return majorFamiliesStr;
    }
    
    public void setMissions(String missionTag) {
        missions = missionTag;
    }
    public String getMissions() {
        return missions;
    }
    
    public void setAntagonist(boolean yn) {
        antagonist = yn;
    }
    public boolean getAntagonist() {
        return antagonist;
    }
    
    public void setLaws(ArrayList<String[]> lawArray) {
        laws = lawArray;
    }
    public ArrayList<String[]> getLaws() {
        return laws;
    }
    
    public void setMilitaryTech(int technology) {
        militaryTech = technology;
    }
    public int getMilitaryTech() {
        return militaryTech;
    }
    
    public void setCivicTech(int technology) {
        civicTech = technology;
    }
    public int getCivicTech() {
        return civicTech;
    }
    
    public void setOratoryTech(int technology) {
        oratoryTech = technology;
    }
    public int getOratoryTech() {
        return oratoryTech;
    }
    
    public void setReligiousTech(int technology) {
        religiousTech = technology;
    }
    public int getReligiousTech() {
        return religiousTech;
    }
    
    public void setAllTech(int technology) { //sets all technology to the same level
        setMilitaryTech(technology);
        setCivicTech(technology);
        setOratoryTech(technology);
        setReligiousTech(technology);
    }
    
    public boolean isTribal() { //Returns true if the country has a tribal government form
        String gov = getGovernment();
        boolean tf = false;
        if (gov.contains("tribal")) {
            tf = true;
        }
        return tf;
    }
    
    public static Country newCountry(int countryID, String countryTag, String countryCulture, String countryReligion, String countryLoc, String countryAdj, 
    String countryHistoricalTag, String countryCapital, String countryFlag, String countryColor, String countryRuler, String gov) {
        Country newCountry = new Country();
        newCountry.setID(countryID);
        newCountry.setTag(countryTag);
        //newPop.setTag(popTag);
        newCountry.setCulture(countryCulture);
        newCountry.setReligion(countryReligion);
        newCountry.setLoc(countryLoc);
        newCountry.setAdj(countryAdj);
        newCountry.setHistoricalTag(countryHistoricalTag);
        newCountry.setCapital(countryCapital);
        newCountry.setFlag(countryFlag);
        newCountry.setColor(countryColor);
        newCountry.setRuler(countryRuler);
        newCountry.setGovernment(gov);
        newCountry.setAntagonist(false); //Set all nations as not Antagonist by default
        
        //By default, set all technology to level 2
        newCountry.setAllTech(2);
        
        return newCountry;
    }
}
