package com.paradoxgameconverters.batoir;
import java.util.ArrayList;
/**
 * Write a description of class Pops here.
 *
 * @author (your name)
 * @version (a version number or a date)
 */
public class Country
{
    private int id; //numerical ID in save file separate from 3-letter tag
    private String culture;
    private String religion;
    private String loc;
    private String adj;
    private String tag;
    private String historicalTag;
    private String capital;
    private String flag;
    private String color;
    private String ruler;
    private boolean hasLand;
    private String updatedTag; //tag generated by algorithm, to prevent conflict with basegame I:R tags
    private String government;
    private ArrayList<String> majorFamilies;
    public Country() {
        int id;
        String culture;
        String religion;
        String loc;
        String adj;
        String tag;
        String historicalTag;
        String capital;
        String flag;
        String color;
        String ruler;
        boolean hasLand;
        String updatedTag;
        ArrayList<String> majorFamilies;
    }
    public void setGovernment(String name) {
        government = name;
    }
    public String getGovernment() {
        return government;
    }
    public void setUpdatedTag(String name) {
        updatedTag = name;
    }
    public String getUpdatedTag() {
        return updatedTag;
    }
    
    public void setHasLand(boolean yn) {
        hasLand = yn;
    }
    public boolean getHasLand() {
        return hasLand;
    }
    public void setHistoricalTag(String name) {
        historicalTag = name;
    }
    public String getHistoricalTag() {
        return historicalTag;
    }
    public void setCapital(String name) {
        capital = name;
    }
    public String getCapital() {
        return capital;
    }
    public void setFlag(String name) {
        flag = name;
    }
    public String getFlag() {
        return flag;
    }
    public void setColor(String name) {
        color = name;
    }
    public String getColor() {
        return color;
    }
    public void setRuler(String name) {
        ruler = name;
    }
    public String getRuler() {
        return ruler;
    }
    
    public void setID(int popID) {
        id = popID;
    }
    public int getID() {
        return id;
    }
    
    public void setLoc(String name) {
        loc = name;
    }
    public String getLoc() {
        return loc;
    }
    public void setAdj(String name) {
        adj = name;
    }
    public String getAdj() {
        return adj;
    }
    
    public void setCulture(String name) {
        culture = name;
    }
    public String getCulture() {
        return culture;
    }
    
    public void setReligion(String name) {
        religion = name;
    }
    public String getReligion() {
        return religion;
    }
    
    public void setTag(String name) {
        tag = name;
    }
    public String getTag() {
        return tag;
    }
    
    public void setMajorFamilies(ArrayList<String> families) {
        majorFamilies = families;
    }
    public ArrayList<String> getMajorFamilies() {
        return majorFamilies;
    }
    
    public static Country newCountry(int countryID, String countryTag, String countryCulture, String countryReligion, String countryLoc, String countryAdj, 
    String countryHistoricalTag, String countryCapital, String countryFlag, String countryColor, String countryRuler, String gov) {
        Country newCountry = new Country();
        newCountry.setID(countryID);
        newCountry.setTag(countryTag);
        //newPop.setTag(popTag);
        newCountry.setCulture(countryCulture);
        newCountry.setReligion(countryReligion);
        newCountry.setLoc(countryLoc);
        newCountry.setAdj(countryAdj);
        newCountry.setHistoricalTag(countryHistoricalTag);
        newCountry.setCapital(countryCapital);
        newCountry.setFlag(countryFlag);
        newCountry.setColor(countryColor);
        newCountry.setRuler(countryRuler);
        newCountry.setGovernment(gov);
        
        return newCountry;
    }
}
