l_english:
 BATOIMPDISPLAYNAME: "Bronze Age:Reborn to Imperator"
 BA: "Bronze Age:Reborn"
 BAFOLDER: "Bronze Age:Reborn Mod Install Directory"
 IMPERATOR: "Imperator"
 BAFOLDERTIP: "The path on your computer where your Bronze Age:Reborn mod is installed"
 IMPERATORFOLDER: "Imperator Install Directory"
 IMPERATORFOLDERTIP: "The path on your computer where Imperator is installed"
 IMPERATORMOD: "Imperator Mod Directory"
 IMPERATORMODTIP: "The path on your computer where Imperator stores mods"
 BAFILE: "Path to the converter executable"
 BAFILETIP: "Path to Converter.jar"
 BASAVE: "Path to the Bronze Age:Reborn savegame"
 BASAVETIP: "Path to your savegame from Bronze Age:Reborn"